FROM nginx:stable-alpine

# Copy index.html to Nginx default directory
COPY index.html /usr/share/nginx/html/index.html

# Nginx will use the default configurations, 
# meaning this index.html exposed on port 80